version: '2'
services:
  # https://hub.docker.com/r/ontotext/graphdb/
  # https://graphdb.ontotext.com/documentation/standard/quick-start-guide.html
  graphdb:
    image: docker-registry.ontotext.com/graphdb-free:9.6.0-adoptopenjdk11
    ports:
      - "7200:7200"
    volumes:
      - ./data:/opt/graphdb/home
