version: '2'
services:
  # https://hub.docker.com/r/ontotext/graphdb/
  # https://graphdb.ontotext.com/documentation/standard/quick-start-guide.html
  graphdb:
    image: ontotext/graphdb:9.7.0-ee
    ports:
      - "7200:7200"
    volumes:
      - ./data:/opt/graphdb/home
